package jr.brian.home.esde.util

object ESDEPreferencesConstants {
    const val PREFS_NAME = "esde_prefs"
    const val KEY_ANIMATION_STYLE = "animation_style"
    const val KEY_ANIMATION_DURATION = "animation_duration"
    const val KEY_ANIMATION_SCALE = "animation_scale"
    const val KEY_BLUR_LEVEL = "blur_level"
    const val KEY_SYSTEM_BLUR_LEVEL = "system_blur_level"
    const val KEY_GAME_BLUR_LEVEL = "game_blur_level"
    const val KEY_DIMMING_LEVEL = "dimming_level"
    const val KEY_BACKGROUND_COLOR = "background_color"
    const val KEY_VIDEO_ENABLED = "video_enabled"
    const val KEY_VIDEO_DELAY = "video_delay"
    const val KEY_VIDEO_AUDIO_ENABLED = "video_audio_enabled"
    const val KEY_VIDEO_SCALE_MODE = "video_scale_mode"
    const val KEY_SYSTEM_BACKGROUND_SCALE_MODE = "system_background_scale_mode"
    const val KEY_GAME_BACKGROUND_SCALE_MODE = "game_background_scale_mode"
    const val KEY_ESDE_ENABLED = "esde_enabled"
    const val KEY_LAST_SELECTED_SYSTEM = "last_selected_system"
    const val KEY_SYSTEM_IMAGE_TYPE = "system_image_type"
    const val KEY_GAME_IMAGE_TYPE = "game_image_type"
    const val KEY_SHOW_SYSTEM_LOGO = "show_system_logo"
    const val KEY_LOGO_ALIGNMENT = "logo_alignment"
    const val KEY_RANDOM_SYSTEM_IMAGE = "random_system_image"
    const val KEY_POWER_EVENTS_ENABLED = "power_events_enabled"
    const val KEY_PERSIST_ON_GAME_LAUNCH = "persist_on_game_launch"
    const val KEY_CUSTOM_SYSTEM_LOGOS_PATH = "custom_system_logos_path"
    const val KEY_CUSTOM_SYSTEM_IMAGES_PATH = "custom_system_images_path"
    const val KEY_SINGLE_SYSTEM_IMAGE_PATH = "single_system_image_path"
    const val KEY_SINGLE_SYSTEM_LOGO_PATH = "single_system_logo_path"
    const val KEY_SINGLE_GAME_IMAGE_PATH = "single_game_image_path"
    const val KEY_SINGLE_GAME_LOGO_PATH = "single_game_logo_path"
    const val KEY_MARQUEE_WIDTH = "marquee_width"
    const val KEY_MARQUEE_HEIGHT = "marquee_height"
    const val KEY_SCREENSAVER_BEHAVIOR = "screensaver_behavior"

    const val KEY_MUSIC_ENABLED = "music_enabled"
    const val KEY_MUSIC_PATH = "music_path"
    const val KEY_MUSIC_SYSTEM_ENABLED = "music_system_enabled"
    const val KEY_MUSIC_GAME_ENABLED = "music_game_enabled"
    const val KEY_MUSIC_SCREENSAVER_ENABLED = "music_screensaver_enabled"
    const val KEY_MUSIC_VIDEO_BEHAVIOR = "music_video_behavior"
    const val KEY_MUSIC_VOLUME = "music_volume"
    const val KEY_MUSIC_USE_SYSTEM_SPECIFIC = "music_use_system_specific"
    const val KEY_MUSIC_LOOP_ENABLED = "music_loop_enabled"

    const val KEY_APP_DRAWER_OPACITY = "app_drawer_opacity"

    const val KEY_MARQUEE_PRESS_SHORTCUT = "marquee_press_shortcut"
    const val KEY_MARQUEE_PRESS_SHORTCUT_APP_PACKAGE = "marquee_press_shortcut_app_package"

    const val KEY_MARQUEE_VISIBLE_PAGES = "marquee_visible_pages"

    const val KEY_MARQUEE_OVERLAY_PAGES = "marquee_overlay_pages"
    const val KEY_SHOW_MARQUEE_FOR_SYSTEM = "show_marquee_for_system"
    const val KEY_SHOW_MARQUEE_FOR_GAME = "show_marquee_for_game"

    const val KEY_GAME_BACKGROUND_DIMMING = "game_background_dimming"
    const val KEY_SYSTEM_BACKGROUND_DIMMING = "system_background_dimming"
    const val KEY_CUSTOM_MEDIA_PATH = "custom_media_path"
    const val KEY_EXCLUDE_EFFECTS_FROM_HOME = "exclude_effects_from_home"
    const val KEY_HIDE_UI_FOR_GAME_BROWSING = "hide_ui_for_game_browsing"
}