package jr.brian.home.esde.util

object ESDEPreferencesConstants {
    const val PREFS_NAME = "esde_prefs"
    const val KEY_ANIMATION_STYLE = "animation_style"
    const val KEY_ANIMATION_DURATION = "animation_duration"
    const val KEY_ANIMATION_SCALE = "animation_scale"
    const val KEY_BLUR_LEVEL = "blur_level"
    const val KEY_SYSTEM_BLUR_LEVEL = "system_blur_level"
    const val KEY_GAME_BLUR_LEVEL = "game_blur_level"
    const val KEY_DIMMING_LEVEL = "dimming_level"
    const val KEY_BACKGROUND_COLOR = "background_color"
    const val KEY_VIDEO_ENABLED = "video_enabled"
    const val KEY_VIDEO_DELAY = "video_delay"
    const val KEY_VIDEO_AUDIO_ENABLED = "video_audio_enabled"
    const val KEY_VIDEO_SCALE_MODE = "video_scale_mode"
    const val KEY_VIDEO_OVERLAY_ENABLED = "video_overlay_enabled"
    const val KEY_SYSTEM_BACKGROUND_SCALE_MODE = "system_background_scale_mode"
    const val KEY_GAME_BACKGROUND_SCALE_MODE = "game_background_scale_mode"
    const val KEY_LAST_SELECTED_SYSTEM = "last_selected_system"
    const val KEY_SYSTEM_IMAGE_TYPE = "system_image_type"
    const val KEY_GAME_IMAGE_TYPE = "game_image_type"
    const val KEY_SHOW_SYSTEM_LOGO = "show_system_logo"
    const val KEY_LOGO_ONLY_MODE = "logo_only_mode"
    const val KEY_LOGO_ALIGNMENT = "logo_alignment"
    const val KEY_LOGO_OFFSET_X = "logo_offset_x"
    const val KEY_LOGO_OFFSET_Y = "logo_offset_y"
    const val KEY_RANDOM_SYSTEM_IMAGE = "random_system_image"
    const val KEY_POWER_EVENTS_ENABLED = "power_events_enabled"
    const val KEY_PERSIST_ON_GAME_LAUNCH = "persist_on_game_launch"
    const val KEY_PERSIST_BACKGROUND_BRIGHTNESS = "persist_background_brightness"
    const val KEY_PERSIST_LOGO_BRIGHTNESS = "persist_logo_brightness"
    const val KEY_CUSTOM_SYSTEM_LOGOS_PATH = "custom_system_logos_path"
    const val KEY_CUSTOM_SYSTEM_IMAGES_PATH = "custom_system_images_path"
    const val KEY_SINGLE_SYSTEM_IMAGE_PATH = "single_system_image_path"
    const val KEY_SINGLE_SYSTEM_LOGO_PATH = "single_system_logo_path"
    const val KEY_SINGLE_GAME_IMAGE_PATH = "single_game_image_path"
    const val KEY_SINGLE_GAME_LOGO_PATH = "single_game_logo_path"
    const val KEY_MARQUEE_WIDTH = "marquee_width"
    const val KEY_MARQUEE_HEIGHT = "marquee_height"
    const val KEY_SCREENSAVER_BEHAVIOR = "screensaver_behavior"
    const val KEY_SCREENSAVER_FLOATY_APP_COUNT = "screensaver_floaty_app_count"

    const val KEY_MUSIC_ENABLED = "music_enabled"
    const val KEY_MUSIC_PATH = "music_path"
    const val KEY_MUSIC_SYSTEM_ENABLED = "music_system_enabled"
    const val KEY_MUSIC_GAME_ENABLED = "music_game_enabled"
    const val KEY_MUSIC_SCREENSAVER_ENABLED = "music_screensaver_enabled"
    const val KEY_MUSIC_VIDEO_BEHAVIOR = "music_video_behavior"
    const val KEY_MUSIC_VOLUME = "music_volume"
    const val KEY_MUSIC_USE_SYSTEM_SPECIFIC = "music_use_system_specific"
    const val KEY_MUSIC_LOOP_ENABLED = "music_loop_enabled"
    const val KEY_MUSIC_IGNORE_AUDIO_FOCUS = "music_ignore_audio_focus"

    const val KEY_APP_DRAWER_OPACITY = "app_drawer_opacity"

    const val KEY_MARQUEE_PRESS_SHORTCUT = "marquee_press_shortcut"
    const val KEY_MARQUEE_PRESS_SHORTCUT_APP_PACKAGE = "marquee_press_shortcut_app_package"

    const val KEY_MARQUEE_VISIBLE_PAGES = "marquee_visible_pages"

    const val KEY_DESCRIPTION_OVERLAY_PAGES = "description_overlay_pages"
    const val KEY_SHOW_MARQUEE_FOR_SYSTEM = "show_marquee_for_system"
    const val KEY_SHOW_MARQUEE_FOR_GAME = "show_marquee_for_game"

    const val KEY_GAME_BACKGROUND_DIMMING = "game_background_dimming"
    const val KEY_SYSTEM_BACKGROUND_DIMMING = "system_background_dimming"
    const val KEY_CUSTOM_MEDIA_PATH = "custom_media_path"
    const val KEY_EXCLUDE_EFFECTS_FROM_HOME = "exclude_effects_from_home"
    const val KEY_EFFECTS_EXCLUDED_PAGES = "effects_excluded_pages"
    const val KEY_HIDE_UI_FOR_GAME_BROWSING = "hide_ui_for_game_browsing"
    const val KEY_MARQUEE_POSITION_LOCKED = "marquee_position_locked"
    const val KEY_GAME_BACKGROUND_SCALE = "android_games_background_scale"
    const val KEY_MARQUEE_MIN_WIDTH_PERCENT = "marquee_min_width_percent"
    const val KEY_OVERLAY_MEDIA_TYPE = "overlay_media_type"
    const val KEY_SELECT_BUTTON_WALLPAPER_TOGGLE = "select_button_wallpaper_toggle"
    const val KEY_WALLPAPER_TOGGLE_TARGET = "wallpaper_toggle_target"

    const val KEY_ROMS_PATH = "roms_path"
    const val KEY_ROMS_PATHS = "roms_paths"
    const val KEY_SYSTEM_APP_MAP = "system_app_map"
    const val KEY_SYSTEM_AUTO_LAUNCH = "system_auto_launch"
    const val KEY_SYSTEM_LAUNCH_TRIGGER_MAP = "system_launch_trigger_map"
    const val KEY_SYSTEM_TOP_SCREEN = "system_top_screen"
    const val KEY_SYSTEM_BG_VIDEO_MUTED = "system_bg_video_muted"
    const val KEY_SYSTEM_BG_VIDEO_LOOPING = "system_bg_video_looping"
    const val KEY_GAME_EMULATOR_MAP = "game_emulator_map"
    const val KEY_GAME_COMMAND_MAP = "game_command_map"
    const val KEY_GAME_CORE_MAP = "game_core_map"
    const val KEY_HIDDEN_GAMES = "hidden_games"
    const val KEY_SAF_TREE_URIS = "saf_tree_uris"
    const val KEY_ROM_SEARCH_USE_WALLPAPER = "rom_search_use_wallpaper"
    const val KEY_ROM_SEARCH_CARD_MEDIA_TYPE = "rom_search_card_media_type"
    const val KEY_ROM_SEARCH_GAME_MEDIA_MAP = "rom_search_game_media_map"
    const val KEY_ROM_SEARCH_HIDE_NO_METADATA = "rom_search_hide_no_metadata"
    const val KEY_ROM_SEARCH_HIDE_NO_IMAGE = "rom_search_hide_no_image"
    const val KEY_ROM_FOCUS_ANIMATION_SPIN = "rom_search_disc_spin"
    const val KEY_ROM_SEARCH_FOCUS_ANIMATION_DISABLED_GAMES = "rom_search_disc_spin_disabled_games"
    const val KEY_ROM_SEARCH_BLACK_BACKGROUND = "rom_search_black_background"
    const val KEY_LOGO_VISIBILITY_ANIMATION = "logo_visibility_animation"
    const val KEY_LOGO_CHANGE_ANIMATION = "logo_change_animation"
    const val KEY_ROM_SEARCH_SHOW_ALL_ANDROID_APPS = "rom_search_show_all_android_apps"
    const val KEY_ROM_SEARCH_PLATFORM_AUTO_FILTER = "rom_search_platform_auto_filter"
    const val KEY_ROM_SEARCH_FOCUS_ANIMATION_DELAY_MS = "rom_search_focus_animation_delay_ms"
}
